# Add application configuration variables here, as shown below.
#
TW_C_KEY:    "ZD1q49IlGKvq256gqu4HQ"
TW_C_SECRET: "FpuoppTkTxy2rMSkzH0bq4aRRuvbrvzKdNCiqLXk8YM"
TW_A_TOKEN:  "169827965-6ak8xjX0txKQpjZcnhDn2pYuyITWFUtJHym6tzrY"
TW_A_SECRET: "rRZ1IxCG8NpN5GT3eyyIheQzi0exExv8OPYrm93img"
M_SECRET: "7x5gocradjx0"
